In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [5]:
df = pd.read_excel(r"C:\Users\sahoo\Downloads\data.xlsx")

In [6]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
len(df)

195

In [9]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [10]:
len(df.columns)

5

In [11]:
df.shape #dimension of the table(no of rows and columns)

(195, 5)

In [12]:
#raw data = missing valuie is present
#clean data = all value present in database
#data cleaning =  convert raw data to clean data
df.isnull() #

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [13]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [14]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [15]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [16]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [18]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [19]:
df.head(4)

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income

PYTHON CONSTRUCTER = __init__

In [20]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

 SLICING IN PANDAS

In [21]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [22]:
df[10:21]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income
20,Belarus,BLR,12.500,54.17000,Upper middle income

In [23]:
df[10:150:20]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
130  Netherlands         NLD     10.200      93.956400          High income

In [24]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [25]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [26]:
df[::-50]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
144,French Polynesia,PYF,16.393,56.8000,High income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
44,Czech Republic,CZE,10.200,74.1104,High income

In [27]:
df['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [30]:
df_cat = df[['CountryName', 'CountryCode','IncomeGroup']]
df_cat

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [31]:
df_num = df[['BirthRate', 'InternetUsers']]

In [32]:
df_num

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [33]:
print(df.columns)
print(df_cat.columns)
print(df_num.columns)

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')
Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')
Index(['BirthRate', 'InternetUsers'], dtype='object')

In [34]:
print(df.shape)
print(df_cat.shape)
print(df_num.shape)

(195, 5)
(195, 3)
(195, 2)

In [35]:
print(df_num.columns)

Index(['BirthRate', 'InternetUsers'], dtype='object')

DESCRIBE= DESCRIPTIVE STATUS

In [36]:
df.describe() # descriptive staticstic

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800